/** Daftar referensi SKPK & Jabatan — Kab. Simeulue */
export const DAFTAR_SKPK: string[] = [
  "Badan Kepegawaian dan Pengembangan Sumber Daya Manusia",
  "Badan Kesatuan Bangsa dan Politik",
  "Badan Penanggulangan Bencana Daerah",
  "Badan Pengelolaan Keuangan Daerah",
  "Badan Perencanaan Pembangunan Daerah",
  "Dinas Kelautan dan Perikanan",
  "Dinas Kepemudaan dan Olah Raga",
  "Dinas Kependudukan dan Pencatatan Sipil",
  "Dinas Kesehatan",
  "Dinas Komunikasi, Informasi dan Persandian",
  "Dinas Lingkungan Hidup",
  "Dinas Pariwisata dan Kebudayaan",
  "Dinas Pekerjaan Umum dan Penataan Ruang",
  "Dinas Pemberdayaan Masyarakat dan Desa",
  "Dinas Pemberdayaan Perempuan, Perlindungan Anak dan Keluarga Berencana",
  "Dinas Penanaman Modal dan Pelayanan Terpadu Satu Pintu",
  "Dinas Pendidikan",
  "Dinas Perhubungan",
  "Dinas Perindustrian, Perdagangan, Koperasi dan UKM",
  "Dinas Perkebunan, Peternakan dan Kesehatan Hewan",
  "Dinas Perpustakaan dan Kearsipan",
  "Dinas Pertanahan",
  "Dinas Pertanian dan Pangan",
  "Dinas Sosial",
  "Dinas Syariat Islam dan Pendidikan Dayah",
  "Dinas Tenaga Kerja Dan Transmigrasi",
  "Inspektorat",
  "Satuan Polisi Pamong Praja dan Wilayatul Hisbah",
  "Sekretariat Baitul Mal",
  "Sekretariat Daerah",
  "Sekretariat Dewan Perwakilan Rakyat Kabupaten",
  "Sekretariat Kecamatan Alafan",
  "Sekretariat Kecamatan Salang",
  "Sekretariat Kecamatan Simeulue Barat",
  "Sekretariat Kecamatan Simeulue Cut",
  "Sekretariat Kecamatan Simeulue Tengah",
  "Sekretariat Kecamatan Simeulue Timur",
  "Sekretariat Kecamatan Teluk Dalam",
  "Sekretariat Kecamatan Teupah Barat",
  "Sekretariat Kecamatan Teupah Selatan",
  "Sekretariat Kecamatan Teupah Tengah",
  "Sekretariat Majelis Adat Aceh",
  "Sekretariat Majelis Pendidikan Daerah",
  "Sekretariat Majelis Permusyawaratan Ulama",
  "UPTD Rumah Sakit Umum Daerah",
];

export const DAFTAR_JABATAN: string[] = [
  "PA (Pengguna Anggaran)",
  "KPA (Kuasa Pengguna Anggaran)",
  "PPK (Pejabat Pembuat Komitmen)",
  "Pejabat Pengadaan",
  "Pokja Pemilihan",
  "PPTK (Pejabat Pelaksana Teknis Kegiatan)",
  "Bendahara",
  "Pengelola PBJ (Pengadaan Barang/Jasa)",
  "Pejabat/Pegawai SKPK (Satuan Kerja Perangkat Kabupaten/Kota)",
  "Penyedia",
  "Pelaku Usaha",
  "Lainnya",
];
